export const templates = [
  {
    id: 1,
    name: "SaaS Dashboard Pro",
    description:
      "Complete admin dashboard with analytics, user management, billing integration, and dark mode support.",
    longDescription:
      "Build powerful admin dashboards with our comprehensive SaaS Dashboard Pro template. Features include real-time analytics charts, user management system, billing and subscription handling, team collaboration tools, and full dark mode support. Built with Next.js 14, TypeScript, and Tailwind CSS for maximum performance and developer experience.",
    category: "saas",
    price: 79,
    image: "/modern-saas-dashboard-dark-theme.jpg",
    tags: ["Next.js", "Tailwind", "Charts", "Auth"],
    featured: true,
    features: [
      "Real-time analytics dashboard",
      "User management system",
      "Billing & subscription integration",
      "Team collaboration tools",
      "Dark/Light mode toggle",
      "Responsive design",
      "TypeScript support",
      "SEO optimized",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Recharts", "NextAuth.js", "Prisma"],
    demoUrl: "https://demo.templateforge.dev/saas-dashboard",
    version: "2.1.0",
    lastUpdated: "2024-01-15",
    downloads: 1250,
    rating: 4.9,
  },
  {
    id: 2,
    name: "E-Commerce Starter Kit",
    description: "Full-featured e-commerce template with cart, checkout, product pages, and Stripe integration.",
    longDescription:
      "Launch your online store quickly with our E-Commerce Starter Kit. This template includes everything you need: product listings with filtering and search, shopping cart with persistent storage, secure checkout with Stripe, order management, customer accounts, and inventory tracking. Optimized for conversions and SEO.",
    category: "ecommerce",
    price: 99,
    image: "/modern-ecommerce-dark.png",
    tags: ["Next.js", "Stripe", "Tailwind", "SEO"],
    featured: true,
    features: [
      "Product catalog with filtering",
      "Shopping cart & wishlist",
      "Stripe payment integration",
      "Order management",
      "Customer accounts",
      "Inventory tracking",
      "SEO optimized pages",
      "Mobile-first design",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Stripe", "Prisma", "PostgreSQL"],
    demoUrl: "https://demo.templateforge.dev/ecommerce",
    version: "3.0.0",
    lastUpdated: "2024-02-01",
    downloads: 2340,
    rating: 4.8,
  },
  {
    id: 3,
    name: "Developer Portfolio",
    description: "Stunning portfolio template for developers and designers with project showcase and blog.",
    longDescription:
      "Showcase your work with our beautiful Developer Portfolio template. Features include animated project galleries, integrated blog with MDX support, contact form, testimonials section, and smooth page transitions. Perfect for developers, designers, and creative professionals looking to make an impression.",
    category: "portfolio",
    price: 49,
    image: "/developer-portfolio-website-dark-theme.jpg",
    tags: ["Next.js", "MDX", "Animations"],
    featured: false,
    features: [
      "Animated project showcase",
      "MDX blog integration",
      "Contact form",
      "Testimonials section",
      "Smooth animations",
      "Resume/CV section",
      "Social media links",
      "SEO optimized",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Framer Motion", "MDX", "Resend"],
    demoUrl: "https://demo.templateforge.dev/portfolio",
    version: "1.5.0",
    lastUpdated: "2024-01-20",
    downloads: 890,
    rating: 4.7,
  },
  {
    id: 4,
    name: "Startup Landing Pro",
    description: "High-converting landing page template for tech startups with waitlist and analytics.",
    longDescription:
      "Convert visitors into customers with our Startup Landing Pro template. Designed for maximum conversions, it includes hero sections with animated graphics, feature highlights, pricing tables, testimonials, FAQ accordion, and integrated waitlist functionality. Perfect for product launches and SaaS startups.",
    category: "landing",
    price: 59,
    image: "/startup-landing-page-dark-theme.jpg",
    tags: ["Next.js", "Tailwind", "Forms"],
    featured: true,
    features: [
      "High-converting hero section",
      "Feature showcase",
      "Pricing tables",
      "Testimonials carousel",
      "FAQ accordion",
      "Waitlist integration",
      "Analytics ready",
      "A/B testing support",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Framer Motion", "React Hook Form"],
    demoUrl: "https://demo.templateforge.dev/startup-landing",
    version: "2.0.0",
    lastUpdated: "2024-01-25",
    downloads: 1560,
    rating: 4.9,
  },
  {
    id: 5,
    name: "Modern Blog",
    description: "Clean blog template with MDX support, SEO optimization, and newsletter integration.",
    longDescription:
      "Create a beautiful blog with our Modern Blog template. Features MDX for rich content, syntax highlighting for code blocks, newsletter subscription, comment system, category and tag filtering, reading time estimates, and table of contents generation. Perfect for tech bloggers and content creators.",
    category: "blog",
    price: 39,
    image: "/modern-blog-website-dark-theme.jpg",
    tags: ["Next.js", "MDX", "SEO"],
    featured: false,
    features: [
      "MDX content support",
      "Syntax highlighting",
      "Newsletter integration",
      "Comment system",
      "Category filtering",
      "Reading time estimate",
      "Table of contents",
      "RSS feed",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "MDX", "Contentlayer", "Resend"],
    demoUrl: "https://demo.templateforge.dev/blog",
    version: "1.8.0",
    lastUpdated: "2024-01-10",
    downloads: 720,
    rating: 4.6,
  },
  {
    id: 6,
    name: "Agency Website",
    description: "Professional agency template with case studies, team pages, and contact forms.",
    longDescription:
      "Present your agency professionally with our Agency Website template. Includes stunning case study layouts, team member profiles, service pages, client testimonials, contact forms with file uploads, and blog integration. Built for creative agencies, design studios, and consulting firms.",
    category: "corporate",
    price: 89,
    image: "/agency-website-dark-theme.jpg",
    tags: ["Next.js", "Tailwind", "CMS"],
    featured: true,
    features: [
      "Case study layouts",
      "Team member profiles",
      "Service pages",
      "Client testimonials",
      "Contact with file upload",
      "Blog integration",
      "CMS ready",
      "Multi-language support",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Sanity CMS", "Framer Motion"],
    demoUrl: "https://demo.templateforge.dev/agency",
    version: "2.2.0",
    lastUpdated: "2024-02-05",
    downloads: 980,
    rating: 4.8,
  },
  {
    id: 7,
    name: "SaaS Landing Page",
    description: "Beautiful landing page for SaaS products with feature highlights and pricing tables.",
    longDescription:
      "Launch your SaaS product with our stunning SaaS Landing Page template. Features include animated hero sections, feature comparisons, interactive pricing calculator, testimonial walls, integration showcases, and CTA optimization. Designed to convert visitors into trial users.",
    category: "saas",
    price: 49,
    image: "/saas-landing-page-dark-theme.jpg",
    tags: ["Next.js", "Tailwind", "Animations"],
    featured: false,
    features: [
      "Animated hero section",
      "Feature comparison",
      "Pricing calculator",
      "Testimonial wall",
      "Integration showcase",
      "CTA optimization",
      "Analytics integration",
      "Fast loading",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Framer Motion"],
    demoUrl: "https://demo.templateforge.dev/saas-landing",
    version: "1.3.0",
    lastUpdated: "2024-01-18",
    downloads: 650,
    rating: 4.5,
  },
  {
    id: 8,
    name: "Online Store",
    description: "Complete e-commerce solution with product filtering, wishlist, and order management.",
    longDescription:
      "Build a complete online store with our Online Store template. Includes advanced product filtering, wishlist functionality, order tracking, customer dashboard, admin panel, inventory management, and multi-currency support. Perfect for retail businesses and online marketplaces.",
    category: "ecommerce",
    price: 119,
    image: "/online-store-website-dark-theme.jpg",
    tags: ["Next.js", "Stripe", "Tailwind"],
    featured: true,
    features: [
      "Advanced product filtering",
      "Wishlist functionality",
      "Order tracking",
      "Customer dashboard",
      "Admin panel",
      "Inventory management",
      "Multi-currency support",
      "Email notifications",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Stripe", "Prisma", "PostgreSQL", "Redis"],
    demoUrl: "https://demo.templateforge.dev/online-store",
    version: "3.2.0",
    lastUpdated: "2024-02-10",
    downloads: 1890,
    rating: 4.9,
  },
  {
    id: 9,
    name: "Creative Portfolio",
    description: "Artistic portfolio template with gallery views, animations, and contact forms.",
    longDescription:
      "Stand out with our Creative Portfolio template. Features masonry gallery layouts, smooth scroll animations, lightbox image viewing, video integration, client project showcase, and creative contact forms. Perfect for photographers, artists, and creative professionals.",
    category: "portfolio",
    price: 59,
    image: "/creative-portfolio-dark.png",
    tags: ["Next.js", "Framer Motion", "Gallery"],
    featured: false,
    features: [
      "Masonry gallery layout",
      "Smooth scroll animations",
      "Lightbox viewing",
      "Video integration",
      "Project showcase",
      "Creative contact form",
      "Social feed integration",
      "Fast image loading",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Framer Motion", "Cloudinary"],
    demoUrl: "https://demo.templateforge.dev/creative-portfolio",
    version: "1.2.0",
    lastUpdated: "2024-01-22",
    downloads: 540,
    rating: 4.7,
  },
  {
    id: 10,
    name: "Product Launch",
    description: "Sleek product launch page with countdown timer, email capture, and social proof.",
    longDescription:
      "Create buzz for your product launch with our Product Launch template. Includes animated countdown timer, email capture with validation, social proof widgets, feature previews, early access tiers, and viral referral system. Optimized for pre-launch marketing campaigns.",
    category: "landing",
    price: 39,
    image: "/product-launch-page-dark-theme.jpg",
    tags: ["Next.js", "Tailwind", "Timer"],
    featured: false,
    features: [
      "Countdown timer",
      "Email capture",
      "Social proof widgets",
      "Feature previews",
      "Early access tiers",
      "Referral system",
      "Progress tracking",
      "Social sharing",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "React Hook Form", "Resend"],
    demoUrl: "https://demo.templateforge.dev/product-launch",
    version: "1.1.0",
    lastUpdated: "2024-01-12",
    downloads: 420,
    rating: 4.6,
  },
  {
    id: 11,
    name: "Corporate Site",
    description: "Enterprise-grade corporate website with about, services, and career pages.",
    longDescription:
      "Build a professional corporate presence with our Corporate Site template. Includes about us pages, service showcases, career portal with job listings, news/press section, investor relations, and contact forms. Designed for enterprises and established businesses.",
    category: "corporate",
    price: 99,
    image: "/corporate-website-dark-theme.jpg",
    tags: ["Next.js", "Tailwind", "SEO"],
    featured: false,
    features: [
      "About us pages",
      "Service showcase",
      "Career portal",
      "News/Press section",
      "Investor relations",
      "Multi-location support",
      "Contact forms",
      "Accessibility compliant",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Sanity CMS", "Algolia"],
    demoUrl: "https://demo.templateforge.dev/corporate",
    version: "2.0.0",
    lastUpdated: "2024-01-28",
    downloads: 760,
    rating: 4.7,
  },
  {
    id: 12,
    name: "Analytics Dashboard",
    description: "Data-driven dashboard with charts, tables, and real-time updates.",
    longDescription:
      "Visualize your data beautifully with our Analytics Dashboard template. Features real-time chart updates, customizable widgets, data export functionality, team collaboration, alert notifications, and mobile-responsive design. Perfect for data-driven applications and business intelligence tools.",
    category: "saas",
    price: 89,
    image: "/analytics-dashboard-dark-theme.png",
    tags: ["Next.js", "Charts", "Real-time"],
    featured: true,
    features: [
      "Real-time chart updates",
      "Customizable widgets",
      "Data export (CSV, PDF)",
      "Team collaboration",
      "Alert notifications",
      "Custom date ranges",
      "Mobile responsive",
      "API integration",
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Recharts", "TanStack Table", "Socket.io"],
    demoUrl: "https://demo.templateforge.dev/analytics",
    version: "2.5.0",
    lastUpdated: "2024-02-08",
    downloads: 1120,
    rating: 4.8,
  },
]

export function getTemplateById(id: number) {
  return templates.find((t) => t.id === id)
}

export function getRelatedTemplates(id: number, category: string) {
  return templates.filter((t) => t.id !== id && t.category === category).slice(0, 3)
}
